version: '3'
services:
  app:
    image: hollfront
    container_name: app
    expose:
      - 80

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

    depends_on:
      - app
=======

>>>>>>> 473eb647cc566a41a41069d39d9d67664e983ab1

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email marsov012@gmail.com -d hollywooddownloader.com --agree-tos
